import { Activity, ArrowLeft, ArrowRight, Check, ChevronDown, ClipboardList, Dumbbell, Medal, ShieldCheck, UserRound } from 'lucide-react'
import { useState } from 'react'
import { useEffect } from 'react'
import type { FormEvent } from 'react'
import * as XLSX from 'xlsx'
import './App.css'
import { useSupabaseRows } from './lib/data'
import jebsResultsUrl from './mocks/24_jebs_results_data.xlsx?url'
import jejsResultsUrl from './mocks/25_jejs_results_data.xlsx?url'

type FormKind = 'profile' | 'physical' | 'motor'
type Answers = Record<string, string>
type ResultRow = { fullName: string; teamAlternateName: string; weightCategoryShortName: string; rank: number; wins: number; losses: number; technicalPointsFor: number; technicalPointsDiff: number; countFights: number; isNotRanked: boolean }
type PhysicalRow = { Estado: string; Estilo: string; Peso: string; 'Envergadura (cm)': string; 'Estatura (cm)': string; 'Prensão manual (D)': string; 'Prensão manual (E)': string; event_identifier: string }
type ProfileRow = { Estado: string; Estilo: string; Peso: string; tempo_pratica: string; local_pratica: string; frequencia_semanal: string; flag_outra_modalidade: string; event_identifier: string }
type MotorRow = { Estado: string; Estilo: string; Peso: string; Avaliação: string; Resultado: string; Competência: string; event_identifier: string }

const states = ['AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS', 'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'SC', 'SE', 'SP', 'TO']
const weights = ['39', '43', '44', '46', '48', '49', '50', '52', '55', '57', '58', '61', '62', '65', '66', '68', '71', '73', '75', '85', '92', '110']
const movements = { Acrobacias: ['Rolo p/ frente', 'Rolo p/ trás', 'Rolo de ombro', 'Estrelinha'], Solo: ['Arranco', 'Cruzeta', 'Nelson', 'Rolê'], Pé: ['Arm Drag', 'Double Leg', 'Submersão', 'Volteio de braço'] }
const details = {
  profile: { label: 'Perfil do atleta', title: 'Cadastro socioesportivo', icon: UserRound, color: 'green' },
  physical: { label: 'Parte física', title: 'Avaliação antropométrica', icon: Dumbbell, color: 'yellow' },
  motor: { label: 'Parte motora', title: 'Avaliação técnica', icon: Activity, color: 'blue' },
}

function App() {
  const requestedForm = new URLSearchParams(window.location.search).get('form')
  const requestedView = new URLSearchParams(window.location.search).get('view')
  if (requestedForm && requestedForm in details) return <CollectionPage initialKind={requestedForm as FormKind} />
  if (requestedView === 'results') return <ResultsPage />
  if (requestedView === 'profiles') return <ProfilesPage />
  if (requestedView === 'physical') return <PhysicalPage />
  if (requestedView === 'motor') return <MotorPage />
  if (requestedView === 'collection') return <CollectionHome />
  return <DashboardPage />
}

function CollectionHome() {
  return <main className="app-shell">
    <PageHeader active="collection" />
    <section className="hero" id="inicio"><div><p className="eyebrow">CENTRO DE INTELIGÊNCIA E RESULTADOS</p><h1>A informação certa para<br /><em>formar campeões.</em></h1><p>Registre dados de atletas com critérios claros e transforme cada avaliação em inteligência para o wrestling brasileiro.</p></div><div className="hero-seal"><ClipboardList size={27} /><strong>Coleta<br />padronizada</strong><span>JEBS · JEJS</span></div></section>
    <section className="collection" id="coleta"><div className="section-heading"><div><p className="eyebrow">NOVA COLETA</p><h2>O que você deseja registrar?</h2></div><p>Três instrumentos, uma base de dados confiável.</p></div><div className="form-cards">
      {(Object.keys(details) as FormKind[]).map((formKind) => { const item = details[formKind]; const Icon = item.icon; return <article className={`form-card ${item.color}`} key={formKind}><span className="card-icon"><Icon /></span><p className="card-kicker">{formKind === 'profile' ? '01' : formKind === 'physical' ? '02' : '03'} · FORMULÁRIO</p><h3>{item.label}</h3><p>{formKind === 'profile' ? 'Histórico, contexto de prática e identificação esportiva.' : formKind === 'physical' ? 'Medidas antropométricas e indicadores de força.' : 'Competências fundamentais por movimento avaliado.'}</p><ul>{formKind === 'profile' ? <><li>1 registro por atleta</li><li>Dados socioesportivos</li></> : formKind === 'physical' ? <><li>1 registro por atleta</li><li>Medidas em centímetros</li></> : <><li>12 movimentos por atleta</li><li>3 competências técnicas</li></>}</ul><a href={`?form=${formKind}`} target="_blank" rel="noopener">Iniciar registro <ArrowRight size={16} /></a></article> })}
    </div></section>
    <section className="data-note"><ShieldCheck size={23} /><div><strong>Dados de menores exigem cuidado.</strong><span>Use apenas os campos necessários à avaliação e respeite a base legal aplicável para coleta e tratamento.</span></div></section>
    <footer>Confederação Brasileira de Wrestling <span>·</span> Plataforma de inteligência esportiva</footer>
  </main>
}

function PageHeader({ active }: { active: string }) { return <header className="topbar"><a className="brand" href="/"><span className="brand-mark"><span>C</span><span>B</span><span>W</span></span><span>CBW <b>Dashboard</b></span></a><nav><a className={active === 'dashboard' ? 'active' : ''} href="/">Painel</a><a className={active === 'results' ? 'active' : ''} href="?view=results">Resultados</a><a className={active === 'profiles' ? 'active' : ''} href="?view=profiles">Atletas</a><a className={active === 'physical' ? 'active' : ''} href="?view=physical">Físico</a><a className={active === 'motor' ? 'active' : ''} href="?view=motor">Técnico</a><a className={active === 'collection' ? 'active' : ''} href="?view=collection">Coleta</a></nav><a className="header-action" href="?form=profile" target="_blank" rel="noopener">Novo registro <ArrowRight size={16} /></a></header> }


function DashboardPage() { return <main className="dashboard-page"><PageHeader active="dashboard" /><section className="dashboard-hero"><div><p className="eyebrow">CENTRO DE INTELIGÊNCIA CBW</p><h1>Dados que fazem<br /><em>o wrestling avançar.</em></h1><p>Explore resultados, desenvolvimento físico e avaliação técnica das competições escolares brasileiras.</p><a className="primary" href="?view=results">Ver resultados oficiais <ArrowRight size={16} /></a></div><div className="event-block"><span>BASE ATUAL</span><strong>JEBS 2024<br />JEJS 2025</strong><small>5 fontes integradas</small></div></section><section className="dashboard-content"><p className="eyebrow">EXPLORAR DADOS</p><h2>Uma visão para cada decisão.</h2><div className="explore-grid"><DashboardLink href="?view=results" icon={<Medal />} title="Resultados" text="Rankings, pódios, vitórias e pontos técnicos por categoria." /><DashboardLink href="?view=profiles" icon={<UserRound />} title="Perfil de atletas" text="Hábitos de prática e contexto de formação esportiva." /><DashboardLink href="?view=physical" icon={<Dumbbell />} title="Desenvolvimento físico" text="Antropometria e força por evento, estado e estilo." /><DashboardLink href="?view=motor" icon={<Activity />} title="Avaliação técnica" text="Domínio de movimentos fundamentais por competência." /></div></section></main> }
function DashboardLink({ href, icon, title, text }: { href: string; icon: React.ReactNode; title: string; text: string }) { return <a className="explore-card" href={href}><span>{icon}</span><h3>{title}</h3><p>{text}</p><ArrowRight size={17} /></a> }

function ProfilesPage() { const { rows } = useSupabaseRows<ProfileRow>('vw_profile_dashboard'); const locations = new Set(rows.map((row) => row.local_pratica).filter(Boolean)).size; const otherSports = rows.filter((row) => row.flag_outra_modalidade.toLowerCase() === 'sim').length; const practices = Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.tempo_pratica || 'Não informado'] = (all[row.tempo_pratica || 'Não informado'] || 0) + 1; return all }, {})).sort((first, second) => second[1] - first[1]); return <main className="analysis-page"><PageHeader active="profiles" /><PageIntro eyebrow="PERFIL DE ATLETAS" title="A base que constrói o atleta." text="Contexto de formação, tempo de prática e hábitos esportivos registrados nos eventos escolares." /><section className="analysis-content"><div className="result-kpis"><Metric label="Perfis coletados" value={String(rows.length)} /><Metric label="Locais de prática" value={String(locations)} /><Metric label="Praticam outra modalidade" value={`${otherSports}`} /><Metric label="Estados na base" value={String(new Set(rows.map((row) => row.Estado)).size)} /></div><div className="analysis-grid"><section className="analysis-panel"><p className="eyebrow">EXPERIÊNCIA</p><h3>Tempo de prática</h3>{practices.slice(0, 5).map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section><section className="analysis-panel"><p className="eyebrow">FORMAÇÃO</p><h3>Onde treinam</h3>{Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.local_pratica || 'Não informado'] = (all[row.local_pratica || 'Não informado'] || 0) + 1; return all }, {})).sort((first, second) => second[1] - first[1]).map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section></div></section></main> }

function PhysicalPage() { const { rows } = useSupabaseRows<PhysicalRow>('vw_physical_dashboard'); const numericAverage = (field: keyof PhysicalRow) => { const values = rows.map((row) => Number(String(row[field]).replace(',', '.'))).filter((value) => value > 0); return values.length ? (values.reduce((total, value) => total + value, 0) / values.length).toFixed(1) : '—' }; const statesRanking = Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.Estado] = (all[row.Estado] || 0) + 1; return all }, {})).sort((first, second) => second[1] - first[1]); return <main className="analysis-page"><PageHeader active="physical" /><PageIntro eyebrow="AVALIAÇÃO FÍSICA" title="Indicadores para orientar o desenvolvimento." text="Medições antropométricas e de força registradas em 302 avaliações de atletas." /><section className="analysis-content"><div className="result-kpis"><Metric label="Avaliações válidas" value={String(rows.length)} /><Metric label="Estatura média" value={`${numericAverage('Estatura (cm)')} cm`} /><Metric label="Envergadura média" value={`${numericAverage('Envergadura (cm)')} cm`} /><Metric label="Prensão direita média" value={numericAverage('Prensão manual (D)')} /></div><div className="analysis-grid"><section className="analysis-panel"><p className="eyebrow">DISTRIBUIÇÃO</p><h3>Avaliações por estado</h3>{statesRanking.slice(0, 7).map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section><section className="analysis-panel"><p className="eyebrow">ESTILOS</p><h3>Registros por modalidade</h3>{Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.Estilo] = (all[row.Estilo] || 0) + 1; return all }, {})).map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section></div></section></main> }

function MotorPage() { const { rows } = useSupabaseRows<MotorRow>('vw_motor_dashboard'); const results = Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.Resultado || 'Sem registro'] = (all[row.Resultado || 'Sem registro'] || 0) + 1; return all }, {})); const competency = Object.entries(rows.reduce<Record<string, number>>((all, row) => { all[row.Competência] = (all[row.Competência] || 0) + 1; return all }, {})); const complete = rows.filter((row) => row.Resultado === 'Completo').length; return <main className="analysis-page"><PageHeader active="motor" /><PageIntro eyebrow="AVALIAÇÃO TÉCNICA" title="O movimento como base da evolução." text="5.424 registros de movimentos fundamentais organizados por competência técnica." /><section className="analysis-content"><div className="result-kpis"><Metric label="Movimentos avaliados" value={String(rows.length)} /><Metric label="Execuções completas" value={String(complete)} /><Metric label="Taxa de domínio" value={rows.length ? `${Math.round((complete / rows.length) * 100)}%` : '—'} /><Metric label="Competências" value={String(competency.length)} /></div><div className="analysis-grid"><section className="analysis-panel"><p className="eyebrow">RESULTADO</p><h3>Qualidade da execução</h3>{results.map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section><section className="analysis-panel"><p className="eyebrow">COBERTURA</p><h3>Movimentos por competência</h3>{competency.map(([label, count]) => <BarRow key={label} label={label} value={count} total={rows.length} />)}</section></div></section></main> }

function PageIntro({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <section className="analysis-hero"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></section> }
function BarRow({ label, value, total }: { label: string; value: number; total: number }) { return <div className="bar-row"><div><span>{label}</span><b>{value}</b></div><i><em style={{ width: `${Math.max(4, (value / total) * 100)}%` }} /></i></div> }

function ResultsPage() {
  const [event, setEvent] = useState<'24_jebs' | '25_jejs'>('25_jejs')
  const [rows, setRows] = useState<ResultRow[]>([])
  useEffect(() => {
    const load = async () => {
      const source = event === '24_jebs' ? jebsResultsUrl : jejsResultsUrl
      const workbook = XLSX.read(await (await fetch(source)).arrayBuffer())
      const sheet = workbook.Sheets[workbook.SheetNames[0]]
      setRows(XLSX.utils.sheet_to_json<ResultRow>(sheet).filter((row) => row.rank && !row.isNotRanked).sort((first, second) => first.rank - second.rank || second.technicalPointsFor - first.technicalPointsFor))
    }
    void load()
  }, [event])
  const fights = rows.reduce((total, row) => total + Number(row.countFights || 0), 0)
  const statesCount = new Set(rows.map((row) => row.teamAlternateName)).size
  const categories = new Set(rows.map((row) => row.weightCategoryShortName)).size
  return <main className="results-page"><PageHeader active="results" /><section className="results-hero"><p className="eyebrow">RESULTADOS OFICIAIS</p><h1>Classificações que contam<br /><em>a história no tapete.</em></h1><p>Dados de desempenho e pódio consolidados a partir dos resultados dos Jogos Escolares.</p></section><section className="results-content"><div className="results-toolbar"><div><p className="eyebrow">RANKING POR EVENTO</p><h2>Atletas classificados</h2></div><label className="event-select"><span>Competição</span><select value={event} onChange={(change) => setEvent(change.target.value as typeof event)}><option value="25_jejs">JEJS 2025 · Sub-17</option><option value="24_jebs">JEBS 2024 · Sub-15</option></select><ChevronDown size={15} aria-hidden="true" /></label></div><div className="result-kpis"><Metric label="Atletas classificados" value={String(rows.length)} /><Metric label="Lutas registradas" value={String(fights)} /><Metric label="Categorias de peso" value={String(categories)} /><Metric label="Estados representados" value={String(statesCount)} /></div><div className="results-layout"><section className="results-table"><div className="table-title"><div><h3>Classificação geral</h3><p>Ordenada por posição na categoria</p></div><span>{event === '25_jejs' ? 'JEJS 2025' : 'JEBS 2024'}</span></div><div className="table-scroll"><table><caption className="sr-only">Classificação dos atletas do evento selecionado</caption><thead><tr><th>Pos.</th><th>Atleta</th><th>UF</th><th>Categoria</th><th>V-D</th><th>Pontos técnicos</th><th>Saldo</th></tr></thead><tbody>{rows.slice(0, 18).map((row) => <tr key={`${row.fullName}-${row.weightCategoryShortName}`}><td className="rank">{row.rank}</td><td><strong>{row.fullName}</strong></td><td><span className="uf">{row.teamAlternateName}</span></td><td>{row.weightCategoryShortName}</td><td>{row.wins}-{row.losses}</td><td className="technical">{row.technicalPointsFor}</td><td className="positive">+{row.technicalPointsDiff}</td></tr>)}</tbody></table></div></section><aside className="podium"><p className="eyebrow">DESTAQUES</p><h3>Ouro por categoria</h3>{rows.filter((row) => row.rank === 1).slice(0, 4).map((row, index) => <div className="podium-row" key={row.fullName}><span>0{index + 1}</span><div><strong>{row.fullName}</strong><small>{row.teamAlternateName} · {row.weightCategoryShortName}</small></div><Medal size={17} /></div>)}</aside></div></section></main>
}

function Metric({ label, value }: { label: string; value: string }) { return <article><span>{label}</span><strong>{value}</strong></article> }

function CollectionPage({ initialKind }: { initialKind: FormKind }) {
  const [kind, setKind] = useState<FormKind | null>(initialKind)
  return <main className="collection-page">{kind ? <AssessmentWizard key={kind} kind={kind} onAnother={() => setKind(null)} /> : <FormPicker onChoose={setKind} />}</main>
}

function FormPicker({ onChoose }: { onChoose: (kind: FormKind) => void }) {
  return <section className="next-form"><p className="eyebrow">NOVO REGISTRO</p><h1>Qual formulário deseja enviar agora?</h1><p>Escolha o próximo instrumento de coleta para este atleta.</p><div className="next-form-grid">{(Object.keys(details) as FormKind[]).map((kind) => { const item = details[kind]; const Icon = item.icon; return <button key={kind} onClick={() => onChoose(kind)}><span className={`card-icon ${item.color}`}><Icon /></span><strong>{item.label}</strong><ArrowRight size={17} /></button> })}</div><a className="finish-link" href="/">Voltar ao painel</a></section>
}

function AssessmentWizard({ kind, onAnother }: { kind: FormKind; onAnother: () => void }) {
  const [step, setStep] = useState(1)
  const [answers, setAnswers] = useState<Answers>({ event: '25_jejs', state: 'SP', style: 'FS', gender: 'M', competency: 'Acrobacias' })
  const [sent, setSent] = useState(false)
    const info = details[kind]; const Icon = info.icon; const totalSteps = 3
    const canAdvance = step !== 1 || Boolean(answers.name?.trim())
  const update = (key: string, value: string) => setAnswers((current) => ({ ...current, [key]: value }))
  const submit = (event: FormEvent) => { event.preventDefault(); setSent(true) }
  if (sent) return <section className="full-success" aria-labelledby="success-title"><span className="success-icon"><Check /></span><p className="eyebrow">REGISTRO CONCLUÍDO</p><h1 id="success-title">Dados recebidos.</h1><p>Deseja enviar outro formulário ou finalizar a coleta?</p><div><button className="primary" onClick={onAnother}>Enviar outro formulário <ArrowRight size={16} /></button><a className="secondary" href="/">Finalizar coleta</a></div></section>
  return <section className="form-screen" aria-labelledby="form-title"><header className="form-screen-header"><a className="brand" href="/"><span className="brand-mark"><span>C</span><span>B</span><span>W</span></span><span>CBW <b>Coleta</b></span></a><a href="/" className="exit-link">Finalizar depois</a></header><div className="form-screen-content"><div className="modal-top"><span className={`modal-icon ${info.color}`}><Icon /></span><div><p className="eyebrow">{info.label}</p><h1 id="form-title">{info.title}</h1></div></div><div className="progress" role="progressbar" aria-label={`Etapa ${step} de ${totalSteps}`} aria-valuemin={1} aria-valuemax={totalSteps} aria-valuenow={step}>{[1, 2, 3].map((number) => <span className={number <= step ? 'done' : ''} key={number}><i>{number < step ? <Check size={12} /> : number}</i><b>{number === 1 ? 'Identificação' : number === 2 ? kind === 'motor' ? 'Avaliação' : 'Dados' : 'Revisão'}</b></span>)}</div><form onSubmit={submit}>
    {step === 1 && <IdentityFields kind={kind} answers={answers} update={update} />}
    {step === 2 && (kind === 'profile' ? <ProfileFields answers={answers} update={update} /> : kind === 'physical' ? <PhysicalFields answers={answers} update={update} /> : <MotorFields answers={answers} update={update} />)}
    {step === 3 && <Review kind={kind} answers={answers} />}
    <div className="form-actions">{step > 1 ? <button type="button" className="secondary" onClick={() => setStep(step - 1)}><ArrowLeft size={16} /> Voltar</button> : <span />}{step < totalSteps ? <button type="button" className="primary" disabled={!canAdvance} onClick={() => setStep(step + 1)}>Continuar <ArrowRight size={16} /></button> : <button className="primary" type="submit">Enviar registro <Check size={16} /></button>}</div>
  </form></div></section>
}

function IdentityFields({ kind, answers, update }: { kind: FormKind; answers: Answers; update: (key: string, value: string) => void }) { return <div className="form-content"><div className="form-intro"><h3>Identifique o atleta</h3><p>Use os mesmos dados de competição para manter os registros conectados.</p></div><div className="field-grid"><Select label="Evento" value={answers.event} options={['24_jebs', '25_jejs']} onChange={(value) => update('event', value)} /><Field label="Nome do atleta" value={answers.name || ''} required onChange={(value) => update('name', value)} /><Select label="Estado (UF)" value={answers.state} options={states} onChange={(value) => update('state', value)} /><Select label="Estilo" value={answers.style} options={['WW', 'FS', 'GR']} onChange={(value) => update('style', value)} /><Select label="Peso (kg)" value={answers.weight || ''} placeholder="Selecione" options={weights} onChange={(value) => update('weight', value)} />{kind !== 'profile' && <Select label="Gênero" value={answers.gender} options={['M', 'W']} onChange={(value) => update('gender', value)} />}{kind === 'profile' && <><Field label="Nascimento" type="date" value={answers.birth || ''} onChange={(value) => update('birth', value)} /><Field label="Escola" value={answers.school || ''} onChange={(value) => update('school', value)} /></>}</div></div> }
function ProfileFields({ answers, update }: Props) { return <div className="form-content"><div className="form-intro"><h3>Contexto de prática</h3><p>As faixas de tempo foram padronizadas para análises consistentes.</p></div><div className="field-grid"><Select label="Tempo de prática" value={answers.practiceTime || ''} placeholder="Selecione" options={['Menos de 6 meses', '6 meses a 1 ano', '1 a 2 anos', '2 a 3 anos', 'Mais de 3 anos']} onChange={(value) => update('practiceTime', value)} /><Select label="Local de prática" value={answers.place || ''} placeholder="Selecione" options={['Projeto social', 'Academia', 'Escola', 'Clube']} onChange={(value) => update('place', value)} /><Select label="Frequência semanal" value={answers.frequency || ''} placeholder="Selecione" options={['1 vez', '2 vezes', '3 vezes', '4 vezes', '5 vezes', 'Mais de 5 vezes']} onChange={(value) => update('frequency', value)} /><Field label="Nome do local de prática" value={answers.locationName || ''} onChange={(value) => update('locationName', value)} /></div><fieldset><legend>Pratica outra modalidade?</legend><div className="choice-row">{['Não pratico', 'Sim'].map((choice) => <label key={choice}><input type="radio" name="otherSport" checked={answers.otherSport === choice} onChange={() => update('otherSport', choice)} />{choice}</label>)}</div>{answers.otherSport === 'Sim' && <div className="check-grid">{['Judô', 'Jiu-Jitsu / BJJ', 'Capoeira', 'MMA', 'Muay Thai', 'Vôlei', 'Outra'].map((item) => <label key={item}><input type="checkbox" onChange={() => update(`sport-${item}`, item)} />{item}</label>)}</div>}</fieldset></div> }
function PhysicalFields({ answers, update }: Props) { const measures = ['Envergadura (cm)', 'Estatura (cm)', 'Prensão manual (D)', 'Prensão manual (E)', 'Envergadura e base', 'Antebraço (D)', 'Antebraço (E)']; return <div className="form-content"><div className="form-intro"><h3>Medidas antropométricas</h3><p>Informe apenas números. Decimais com vírgula ou ponto são aceitos.</p></div><div className="field-grid">{measures.map((measure) => <Field key={measure} label={measure} type="number" value={answers[measure] || ''} onChange={(value) => update(measure, value)} />)}<Select label="Colocação (opcional)" value={answers.placement || ''} placeholder="Não se aplica" options={['1', '2', '3']} onChange={(value) => update('placement', value)} /></div></div> }
function MotorFields({ answers, update }: Props) { const competency = answers.competency || 'Acrobacias'; return <div className="form-content"><div className="form-intro"><h3>Avaliação por movimento</h3><p>Complete os quatro movimentos desta competência e troque de aba para continuar.</p></div><div className="competencies">{Object.keys(movements).map((item) => <button type="button" className={competency === item ? 'selected' : ''} key={item} onClick={() => update('competency', item)}>{item}</button>)}</div><div className="movement-list">{movements[competency as keyof typeof movements].map((movement) => <div className="movement" key={movement}><strong>{movement}</strong><Select label="Resultado" value={answers[movement] || ''} placeholder="Selecione" options={['Completo', 'Incompleto', 'Não Fez', 'Não Sabe']} onChange={(value) => update(movement, value)} /></div>)}</div></div> }
function Review({ kind, answers }: { kind: FormKind; answers: Answers }) { const labels = kind === 'profile' ? ['event', 'name', 'state', 'style', 'weight', 'practiceTime', 'frequency'] : kind === 'physical' ? ['event', 'name', 'state', 'style', 'weight', 'gender', 'Envergadura (cm)', 'Estatura (cm)'] : ['event', 'name', 'state', 'style', 'weight', 'gender', 'competency']; return <div className="form-content"><div className="form-intro"><h3>Revise antes de enviar</h3><p>Os dados serão associados ao evento e à categoria indicados.</p></div><dl className="review-list">{labels.map((key) => <div key={key}><dt>{key.replace('event', 'Evento').replace('name', 'Atleta').replace('state', 'Estado').replace('style', 'Estilo').replace('weight', 'Peso').replace('gender', 'Gênero').replace('competency', 'Competência')}</dt><dd>{answers[key] || 'Não informado'}</dd></div>)}</dl></div> }
type Props = { answers: Answers; update: (key: string, value: string) => void }
function Field({ label, value, onChange, type = 'text', required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="field"><span>{label}{required && <b> *</b>}</span><input required={required} type={type} value={value} onChange={(event) => onChange(event.target.value)} /></label> }
function Select({ label, value, options, onChange, placeholder }: { label: string; value: string; options: string[]; onChange: (value: string) => void; placeholder?: string }) { return <label className="field"><span>{label}</span><div className="select-wrap"><select value={value} onChange={(event) => onChange(event.target.value)}><option value="">{placeholder || options[0]}</option>{options.map((option) => <option key={option} value={option}>{option}{label.includes('Peso') ? ' kg' : ''}</option>)}</select><ChevronDown size={15} aria-hidden="true" /></div></label> }
export default App